should_global_factor_list:
  - throw
  - return
  - log
  - ApiResult
  - LogUtil


project_path: /Users/td/code/project/yuntu-aml
messages_path: /Users/helloworld/code/pro/messages.properties
messages_cn_path: /Users/helloworld/code/pro/messages_cn.properties
messages_en_path: /Users/helloworld/code/pro/messages_en.properties
locale_message_enum_path: /Users/helloworld/code/pro/LocaleMessageEnum.java


error_log_path: /Users/helloworld/code/code_everyday/demo_code/src/com/wy/global/log/error.log

info_log_path: /Users/td/code/project/code_everyday/demo_code/src/com/wy/global/log/info.xlsx

